version: '3.4'

services:
  collection_tracker:
    image: collection_tracker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
      - 9229:9229
    command: ["NODE_ENV=production","PORT=3001",  "DB_PORT=3306", "DB_HOST=srv-captain--mysql-db", "DB_USER=root", "DB_PASSWORD=thina@2023", "DB_NAME=collection_tracker247_db", "DB_DIALECT=mysql", "SITE=https://collection-tracker.builds.saincrafttechnologies.com","PUBLIC=https://saincrafttechnologies-static-public-2023.fra1.cdn.digitaloceanspaces.com/storekeeperapp/public","node", "--inspect=0.0.0.0:9229", "main.js"]
