version: '3.4'

services:
  collection_tracker:
    image: collection_tracker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
