module.exports = async (app) => {
    app.use('/', require('./backend/routes/home'));
    // app.use('/currencies', require('./backend/routes/currencies'));
    app.use('/superadmin', require('./backend/routes/superadmin_home'));
    // app.use('/admin', require('./backend/routes/admin_home'));
    // app.use('/business', require('./backend/routes/business_home'));
    app.use('/categories', require('./backend/routes/categories'));
    app.use('/charges', require('./backend/routes/charges'));
    app.use('/charges/categories', require('./backend/routes/charges'));
    app.use('/employees', require('./backend/routes/employees'));
    app.use('/employers', require('./backend/routes/employers'));
    // app.use('/superadmin/users', require('./backend/routes/backend/users'));
    // app.use('/sdealers', require('./backend/routes/software_dealers_home'));
    // app.use('/software/dealers', require('./backend/routes/backend/software_dealers'));
    app.use('/auth', require('./backend/routes/auth'));
    app.use('/theme/toggle', require('./backend/routes/translate'));
    /** SuperADMIN */
    // app.use('/businesses', require('./backend/routes/backend/businesses'));
    // app.use('/niches', require('./backend/routes/backend/niches'));
    // app.use('/stores', require('./backend/routes/backend/stores'));
    // app.use('/sessions', require('./backend/routes/backend/sessions'));
    // app.use('/settings', require('./backend/routes/backend/settings'));
    app.use('/tasks/schedules', require('./backend/routes/backend/schedules'));
    app.use('/tasks', require('./backend/routes/backend/tasks'));
    app.use('/schedules', require('./backend/routes/backend/schedules'));
    app.use('/users', require('./backend/routes/backend/users'));
    // app.use('/customers', require('./backend/routes/backend/customers'));
    // app.use('/personels', require('./backend/routes/backend/personels'));
    app.use('/menus', require('./backend/routes/backend/menus'));
    // app.use('/items', require('./backend/routes/backend/items'));
    // app.use('/categories', require('./backend/routes/backend/item_categories'));
    // app.use('/products', require('./backend/routes/backend/products'));
    // app.use('/translate', require('./backend/routes/translate'));
    // app.use('/countries', require('./backend/routes/countries'));
    // app.use('/stocks/in', require('./backend/routes/backend/stockIns'));
    // app.use('/departments', require('./backend/routes/backend/departments'));
    // app.use('/permissions', require('./backend/routes/backend/permissions'));
    // app.use('/accountants', require('./backend/routes/backend/accountants'));
    // app.use('/classes', require('./backend/routes/backend/classes'));
    // app.use('/librarians', require('./backend/routes/backend/librarians'));
    // app.use('/classrooms', require('./backend/routes/backend/classrooms'));
    // app.use('/pos', require('./backend/routes/backend/pos'));
    // app.use('/grades', require('./backend/routes/backend/grades'));
    // app.use('/categories', require('./backend/routes/backend/item_categories'));
    // app.use('/marks', require('./backend/routes/backend/marks'));
    // app.use('/vehicles', require('./backend/routes/backend/vehicles'));
    // app.use('/syllabus', require('./backend/routes/backend/syllabuses'));
    // app.use('/attendances', require('./backend/routes/backend/attendances'));
    // app.use('/buses', require('./backend/routes/backend/buses'));
    // app.use('/books', require('./backend/routes/backend/books'));
    // app.use('/profile', require('./backend/routes/backend/profile'));
    // app.use('/deductions', require('./backend/routes/backend/deductions'));
    // app.use('/expenses', require('./backend/routes/backend/expenseCategories'));
    // app.use('/invoices', require('./backend/routes/backend/invoices'));
    // app.use('/academics', require('./backend/routes/backend/academics'));
}